console.log("Lyric Video Generator - Help")
console.log("")
console.log("Commands:")
console.log("   npm run setup")
console.log("")
console.log("Usage:")
console.log("   Upload your lyrics file to ./public/lyrics")
console.log("   Upload your audio file to ./public/audio")
console.log("   Upload your background image to ./public/images")
console.log("   npm run start")
console.log("")
console.log("Wait, and then you'll see your lyric video in ./output")